elt_dbt: # Tên profile phải khớp với file dbt_project.yml ở trên
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres      # Tên service trong docker-compose
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: public      # Chúng ta sẽ lưu bảng sạch vào schema public
      threads: 1